<?php

use App\Http\Controllers\Api\AuditLogController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AnalyticsBacktestController;
use App\Http\Controllers\Api\AutomationController;
use App\Http\Controllers\Api\ObservabilityController;
use App\Http\Controllers\Api\GovernanceController;
use App\Http\Controllers\Api\IntelligenceController;
use App\Http\Controllers\Api\AdvancedIntelligenceController;
use App\Http\Controllers\Api\BrokerAccountController;
use App\Http\Controllers\Api\FleetController;
use App\Http\Controllers\Api\HardeningController;
use App\Http\Controllers\Api\IndicatorController;
use App\Http\Controllers\Api\MarketDataController;
use App\Http\Controllers\Api\MarketScannerController;
use App\Http\Controllers\Api\Mt5BridgeController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PasswordResetController;
use App\Http\Controllers\Api\PositionController;
use App\Http\Controllers\Api\RiskEngineController;
use App\Http\Controllers\Api\ExecutionEngineController;
use App\Http\Controllers\Api\TradeManagementController;
use App\Http\Controllers\Api\RiskProfileController;
use App\Http\Controllers\Api\ServiceHeartbeatController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\SignalController;
use App\Http\Controllers\Api\SimulationOrderController;
use App\Http\Controllers\Api\StrategyController;
use App\Http\Controllers\Api\StrategyEngineController;
use App\Http\Controllers\Api\SystemController;
use App\Http\Controllers\Api\TradeIntentController;
use App\Http\Controllers\Api\TradingInstrumentController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\UserPreferenceController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('web')->group(function (): void {
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('/auth/password/request', [PasswordResetController::class, 'request'])->middleware('throttle:3,1');
    Route::post('/auth/password/reset', [PasswordResetController::class, 'reset'])->middleware('throttle:5,1');
    Route::get('/system/status', [SystemController::class, 'status']);
    Route::get('/simulation/status', [SystemController::class, 'status']);

    // Phase 15 — public health probes (no secrets; no trading actions)
    Route::get('/health', [ObservabilityController::class, 'health'])->middleware('throttle:health');
    Route::get('/health/liveness', [ObservabilityController::class, 'liveness'])->middleware('throttle:health');
    Route::get('/health/readiness', [ObservabilityController::class, 'readiness'])->middleware('throttle:health');
    Route::get('/health/trading-readiness', [ObservabilityController::class, 'tradingReadiness'])->middleware('throttle:health');

    Route::middleware(['auth:sanctum', 'active'])->group(function (): void {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/dashboard', [SystemController::class, 'dashboard'])->middleware('permission:dashboard.view');

        Route::get('/users', [UserController::class, 'index'])->middleware('permission:users.view');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:users.create');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:users.update');
        Route::post('/users/{user}/activate', [UserController::class, 'activate'])->middleware('permission:users.status');
        Route::post('/users/{user}/suspend', [UserController::class, 'suspend'])->middleware('permission:users.status');
        Route::post('/users/{user}/disable', [UserController::class, 'disable'])->middleware('permission:users.status');

        Route::get('/strategies', [StrategyController::class, 'index'])->middleware('permission:strategies.view');
        Route::post('/strategies', [StrategyController::class, 'store'])->middleware('permission:strategies.create');
        Route::get('/strategies/{strategy}', [StrategyController::class, 'show'])->middleware('permission:strategies.view');
        Route::put('/strategies/{strategy}', [StrategyController::class, 'update'])->middleware('permission:strategies.update');
        Route::post('/strategies/{strategy}/enable', [StrategyController::class, 'enable'])->middleware('permission:strategies.update');
        Route::post('/strategies/{strategy}/disable', [StrategyController::class, 'disable'])->middleware('permission:strategies.update');
        Route::post('/strategies/{strategy}/evaluate', [StrategyEngineController::class, 'evaluate'])->middleware('permission:strategies.view');
        Route::get('/strategies/{strategy}/performance', [StrategyEngineController::class, 'performance'])->middleware('permission:strategies.view');

        Route::get('/strategy-engine/catalog', [StrategyEngineController::class, 'catalog'])->middleware('permission:strategies.view');
        Route::get('/strategy-engine/health', [StrategyEngineController::class, 'health'])->middleware('permission:trading.read');
        Route::post('/strategy-engine/run', [StrategyEngineController::class, 'run'])->middleware('permission:strategies.update');
        Route::post('/strategy-engine/scan', [StrategyEngineController::class, 'scan'])->middleware('permission:strategies.view');
        Route::get('/strategy-engine/matrix', [StrategyEngineController::class, 'matrix'])->middleware('permission:strategies.view');
        Route::post('/strategy-engine/confluence', [StrategyEngineController::class, 'confluence'])->middleware('permission:strategies.view');

        Route::get('/scanner/health', [MarketScannerController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/scanner/universe', [MarketScannerController::class, 'universe'])->middleware('permission:strategies.view');
        Route::get('/scanner/board', [MarketScannerController::class, 'board'])->middleware('permission:strategies.view');
        Route::post('/scanner/run', [MarketScannerController::class, 'run'])->middleware('permission:strategies.update');
        Route::get('/scanner/matrix', [MarketScannerController::class, 'matrix'])->middleware('permission:strategies.view');
        Route::post('/scanner/matrix', [MarketScannerController::class, 'matrix'])->middleware('permission:strategies.view');
        Route::get('/scanner/configs', [MarketScannerController::class, 'configs'])->middleware('permission:strategies.view');
        Route::put('/scanner/configs', [MarketScannerController::class, 'upsertConfig'])->middleware('permission:strategies.update');
        Route::get('/scanner/runs', [MarketScannerController::class, 'runs'])->middleware('permission:strategies.view');
        Route::get('/scanner/queue', [MarketScannerController::class, 'queue'])->middleware('permission:signals.view');
        Route::get('/scanner/candidates/{candidate}', [MarketScannerController::class, 'showCandidate'])->middleware('permission:signals.view');
        Route::post('/scanner/candidates/{candidate}/dismiss', [MarketScannerController::class, 'dismiss'])->middleware('permission:signals.view');
        Route::post('/scanner/candidates/{candidate}/invalidate', [MarketScannerController::class, 'invalidate'])->middleware('permission:signals.view');
        Route::post('/scanner/candidates/{candidate}/mark-simulate', [MarketScannerController::class, 'markSimulate'])->middleware('permission:simulation_lifecycle.create');
        Route::get('/scanner/alerts', [MarketScannerController::class, 'alerts'])->middleware('permission:notifications.view');
        Route::post('/scanner/expire-due', [MarketScannerController::class, 'expireDue'])->middleware('permission:signals.view');

        Route::get('/risk-profiles', [RiskProfileController::class, 'index'])->middleware('permission:risk_profiles.view');
        Route::post('/risk-profiles', [RiskProfileController::class, 'store'])->middleware('permission:risk_profiles.create');
        Route::put('/risk-profiles/{riskProfile}', [RiskProfileController::class, 'update'])->middleware('permission:risk_profiles.update');

        Route::get('/risk-engine/health', [RiskEngineController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/risk-engine/catalog', [RiskEngineController::class, 'catalog'])->middleware('permission:risk_engine.view');
        Route::get('/risk-engine/dashboard', [RiskEngineController::class, 'dashboard'])->middleware('permission:risk_engine.view');
        Route::get('/risk-engine/decisions', [RiskEngineController::class, 'decisions'])->middleware('permission:risk_engine.view');
        Route::get('/risk-engine/decisions/{riskDecision}', [RiskEngineController::class, 'showDecision'])->middleware('permission:risk_engine.view');
        Route::get('/risk-engine/plans/{proposedPlan}', [RiskEngineController::class, 'showPlan'])->middleware('permission:risk_engine.view');
        Route::post('/risk-engine/evaluate/{tradeIntent}', [RiskEngineController::class, 'evaluate'])->middleware('permission:risk_engine.evaluate');
        Route::get('/risk-engine/locks', [RiskEngineController::class, 'locks'])->middleware('permission:risk_engine.view');
        Route::post('/risk-engine/locks', [RiskEngineController::class, 'createLock'])->middleware('permission:risk_engine.lock');
        Route::post('/risk-engine/locks/{riskLock}/release', [RiskEngineController::class, 'releaseLock'])->middleware('permission:risk_engine.lock');
        Route::post('/risk-engine/assert-gate', [RiskEngineController::class, 'assertGate'])->middleware('permission:risk_engine.view');

        Route::get('/broker-accounts', [BrokerAccountController::class, 'index'])->middleware('permission:broker_accounts.view');
        Route::post('/broker-accounts', [BrokerAccountController::class, 'store'])->middleware('permission:broker_accounts.create');
        Route::put('/broker-accounts/{brokerAccount}', [BrokerAccountController::class, 'update'])->middleware('permission:broker_accounts.update');

        Route::get('/settings', [SettingController::class, 'index'])->middleware('permission:settings.view');
        Route::put('/settings/{key}', [SettingController::class, 'update'])->middleware('permission:settings.update');
        Route::put('/emergency-stop', [SettingController::class, 'emergencyStop'])->middleware('permission:emergency_stop.manage');
        Route::get('/preferences', [UserPreferenceController::class, 'show'])->middleware('permission:preferences.view');
        Route::put('/preferences', [UserPreferenceController::class, 'update'])->middleware('permission:preferences.update');
        Route::get('/notifications', [NotificationController::class, 'index'])->middleware('permission:notifications.view');
        Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->middleware('permission:notifications.update');
        Route::get('/audit-logs', [AuditLogController::class, 'index'])->middleware('permission:audit_logs.view');
        Route::post('/simulation/orders', [SimulationOrderController::class, 'store'])->middleware('permission:simulation_orders.create');

        Route::get('/instruments', [TradingInstrumentController::class, 'index'])->middleware('permission:trading.read');
        Route::get('/instruments/{instrument}', [TradingInstrumentController::class, 'show'])->middleware('permission:trading.read');
        Route::get('/signals', [SignalController::class, 'index'])->middleware('permission:signals.view');
        Route::post('/signals/expire-due', [SignalController::class, 'expireDue'])->middleware('permission:signals.view');
        Route::get('/signals/{signal}', [SignalController::class, 'show'])->middleware('permission:signals.view');
        Route::post('/signals/{signal}/trade-intent', [SignalController::class, 'createIntent'])->middleware('permission:simulation_lifecycle.create');
        Route::post('/signals/{signal}/invalidate', [SignalController::class, 'invalidate'])->middleware('permission:signals.view');

        Route::get('/trade-intents', [TradeIntentController::class, 'index'])->middleware('permission:trading.read');
        Route::post('/trade-intents', [TradeIntentController::class, 'store'])->middleware('permission:simulation_lifecycle.create');
        Route::get('/trade-intents/{tradeIntent}', [TradeIntentController::class, 'show'])->middleware('permission:trading.read');
        Route::post('/trade-intents/{tradeIntent}/evaluate', [TradeIntentController::class, 'evaluate'])->middleware('permission:simulation_lifecycle.evaluate');
        Route::post('/trade-intents/{tradeIntent}/execute', [TradeIntentController::class, 'execute'])->middleware('permission:simulation_lifecycle.execute');

        Route::get('/orders', [OrderController::class, 'index'])->middleware('permission:trading.read');
        Route::get('/orders/{order}', [OrderController::class, 'show'])->middleware('permission:trading.read');
        Route::post('/orders/{order}/cancel', [OrderController::class, 'cancel'])->middleware('permission:simulation_orders.cancel');
        Route::get('/positions', [PositionController::class, 'index'])->middleware('permission:trading.read');
        Route::get('/positions/{position}', [PositionController::class, 'show'])->middleware('permission:trading.read');
        Route::post('/positions/{position}/close', [PositionController::class, 'close'])->middleware('permission:simulation_positions.manage');
        Route::post('/positions/{position}/partial-close', [PositionController::class, 'partialClose'])->middleware('permission:simulation_positions.manage');
        Route::put('/positions/{position}/stop-loss', [PositionController::class, 'modifyStopLoss'])->middleware('permission:simulation_positions.manage');
        Route::put('/positions/{position}/take-profit', [PositionController::class, 'modifyTakeProfit'])->middleware('permission:simulation_positions.manage');
        Route::put('/positions/{position}/protection', [PositionController::class, 'modifyProtection'])->middleware('permission:simulation_positions.manage');
        Route::get('/heartbeats', [ServiceHeartbeatController::class, 'index'])->middleware('permission:trading.read');

        Route::get('/market/snapshot', [MarketDataController::class, 'snapshot'])->middleware('permission:trading.read');
        Route::get('/market/quotes', [MarketDataController::class, 'quotes'])->middleware('permission:trading.read');
        Route::get('/market/quotes/{symbol}', [MarketDataController::class, 'quote'])->middleware('permission:trading.read');
        Route::get('/market/candles/{symbol}', [MarketDataController::class, 'candles'])->middleware('permission:trading.read');
        Route::get('/market/candles/{symbol}/closed', [MarketDataController::class, 'closedCandles'])->middleware('permission:trading.read');
        Route::get('/market/symbols', [MarketDataController::class, 'symbols'])->middleware('permission:trading.read');
        Route::get('/market/sessions', [MarketDataController::class, 'sessions'])->middleware('permission:trading.read');
        Route::get('/market/status/{symbol}', [MarketDataController::class, 'status'])->middleware('permission:trading.read');
        Route::get('/market/health', [MarketDataController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/market/snapshots/latest', [MarketDataController::class, 'latestPersisted'])->middleware('permission:trading.read');
        Route::get('/market/monitored', [MarketDataController::class, 'monitored'])->middleware('permission:trading.read');
        Route::put('/market/monitored', [MarketDataController::class, 'monitored'])->middleware('permission:market.configure');
        Route::post('/market/symbols/sync', [MarketDataController::class, 'syncSymbols'])->middleware('permission:market.configure');
        Route::post('/market/backfill', [MarketDataController::class, 'backfill'])->middleware('permission:market.configure');
        Route::post('/market/quality-check', [MarketDataController::class, 'qualityCheck'])->middleware('permission:trading.read');
        Route::get('/market/extension-hooks', [MarketDataController::class, 'extensionHooks'])->middleware('permission:trading.read');

        Route::get('/indicators/catalog', [IndicatorController::class, 'catalog'])->middleware('permission:trading.read');
        Route::get('/indicators/health', [IndicatorController::class, 'health'])->middleware('permission:trading.read');
        Route::post('/indicators/compute', [IndicatorController::class, 'compute'])->middleware('permission:trading.read');
        Route::post('/indicators/batch', [IndicatorController::class, 'batch'])->middleware('permission:trading.read');
        Route::get('/indicators/{indicator}/series', [IndicatorController::class, 'series'])->middleware('permission:trading.read');

        Route::get('/mt5/status', [Mt5BridgeController::class, 'status'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/health', [Mt5BridgeController::class, 'proxyHealth'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/terminal', [Mt5BridgeController::class, 'proxyTerminal'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/account', [Mt5BridgeController::class, 'proxyAccount'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/symbols', [Mt5BridgeController::class, 'proxySymbols'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/symbols/{symbol}', [Mt5BridgeController::class, 'proxySymbol'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/quotes/{symbol}', [Mt5BridgeController::class, 'proxyQuote'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/candles/{symbol}', [Mt5BridgeController::class, 'proxyCandles'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/positions', [Mt5BridgeController::class, 'proxyPositions'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/orders', [Mt5BridgeController::class, 'proxyOrders'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/history/orders', [Mt5BridgeController::class, 'proxyHistoryOrders'])->middleware('permission:mt5.read');
        Route::get('/mt5/bridge/history/deals', [Mt5BridgeController::class, 'proxyHistoryDeals'])->middleware('permission:mt5.read');
        Route::get('/mt5/connections', [Mt5BridgeController::class, 'connections'])->middleware('permission:mt5.read');
        Route::post('/mt5/connections', [Mt5BridgeController::class, 'storeConnection'])->middleware('permission:mt5.connections.manage');
        Route::post('/mt5/connections/{connection}/test', [Mt5BridgeController::class, 'testConnection'])->middleware('permission:mt5.connections.manage');
        Route::post('/mt5/connections/{connection}/enable', [Mt5BridgeController::class, 'enableConnection'])->middleware('permission:mt5.connections.manage');
        Route::delete('/mt5/connections/{connection}', [Mt5BridgeController::class, 'destroyConnection'])->middleware('permission:mt5.connections.manage');
        Route::post('/mt5/connections/{connection}/sync', [Mt5BridgeController::class, 'syncConnection'])->middleware('permission:mt5.sync');
        Route::get('/mt5/mappings/{mapping}/positions', [Mt5BridgeController::class, 'mappingPositions'])->middleware('permission:mt5.read');
        Route::get('/mt5/mappings/{mapping}/orders', [Mt5BridgeController::class, 'mappingOrders'])->middleware('permission:mt5.read');
        Route::get('/mt5/mappings/{mapping}/deals', [Mt5BridgeController::class, 'mappingDeals'])->middleware('permission:mt5.read');
        Route::post('/mt5/mappings/{mapping}/reconcile', [Mt5BridgeController::class, 'reconcileMapping'])->middleware('permission:mt5.reconcile');
        Route::get('/mt5/reconciliation-runs', [Mt5BridgeController::class, 'reconciliationRuns'])->middleware('permission:mt5.read');
        Route::get('/mt5/reconciliation-runs/{run}', [Mt5BridgeController::class, 'reconciliationRun'])->middleware('permission:mt5.read');

        Route::get('/execution/health', [ExecutionEngineController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/execution/dashboard', [ExecutionEngineController::class, 'dashboard'])->middleware('permission:execution.view');
        Route::get('/execution/metrics', [ExecutionEngineController::class, 'metrics'])->middleware('permission:execution.view');
        Route::post('/execution/accounts/{brokerAccount}/verify', [ExecutionEngineController::class, 'verifyAccount'])->middleware('permission:execution.confirm');
        Route::post('/execution/intents/{tradeIntent}/confirmations', [ExecutionEngineController::class, 'startConfirmation'])->middleware('permission:execution.confirm');
        Route::post('/execution/confirmations/{confirmation}/step2', [ExecutionEngineController::class, 'completeConfirmation'])->middleware('permission:execution.confirm');
        Route::post('/execution/demo/submit', [ExecutionEngineController::class, 'submit'])->middleware('permission:execution.execute');
        Route::get('/execution/commands/{executionCommand}', [ExecutionEngineController::class, 'showCommand'])->middleware('permission:execution.view');
        Route::post('/execution/commands/{executionCommand}/recover', [ExecutionEngineController::class, 'recover'])->middleware('permission:execution.recover');
        Route::post('/execution/reconcile', [ExecutionEngineController::class, 'reconcile'])->middleware('permission:execution.reconcile');

        Route::get('/trade-management/status', [TradeManagementController::class, 'status'])->middleware('permission:trade_management.view');
        Route::get('/trade-management/health', [TradeManagementController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/trade-management/dashboard', [TradeManagementController::class, 'dashboard'])->middleware('permission:trade_management.view');
        Route::get('/trade-management/policies', [TradeManagementController::class, 'policies'])->middleware('permission:trade_management.view');
        Route::get('/trade-management/summaries', [TradeManagementController::class, 'summaries'])->middleware('permission:trade_management.view');
        Route::post('/trade-management/monitor/tick', [TradeManagementController::class, 'monitorTick'])->middleware('permission:trade_management.manage');
        Route::post('/trade-management/recover', [TradeManagementController::class, 'recoverAll'])->middleware('permission:trade_management.recover');
        Route::post('/trade-management/close-all', [TradeManagementController::class, 'closeAll'])->middleware('permission:trade_management.close_all');
        Route::get('/positions-managed', [TradeManagementController::class, 'positions'])->middleware('permission:trade_management.view');
        Route::get('/positions-managed/{position}', [TradeManagementController::class, 'showPosition'])->middleware('permission:trade_management.view');
        Route::post('/positions-managed/{position}/pause', [TradeManagementController::class, 'pause'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/resume', [TradeManagementController::class, 'resume'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/evaluate', [TradeManagementController::class, 'evaluate'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/close/prepare', [TradeManagementController::class, 'prepareClose'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/close/confirm', [TradeManagementController::class, 'confirmClose'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/partial-close/prepare', [TradeManagementController::class, 'preparePartial'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/partial-close/confirm', [TradeManagementController::class, 'confirmPartial'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/protection/prepare', [TradeManagementController::class, 'prepareProtection'])->middleware('permission:trade_management.manage');
        Route::post('/positions-managed/{position}/protection/confirm', [TradeManagementController::class, 'confirmProtection'])->middleware('permission:trade_management.manage');
        Route::get('/positions-managed/{position}/events', [TradeManagementController::class, 'events'])->middleware('permission:trade_management.view');
        Route::post('/trade-management/actions/{action}/recover', [TradeManagementController::class, 'recover'])->middleware('permission:trade_management.recover');

        // Phase 12 — Analytics + Backtesting (research only; zero broker writes)
        Route::get('/analytics/health', [AnalyticsBacktestController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/analytics/dashboard', [AnalyticsBacktestController::class, 'dashboard'])->middleware('permission:analytics.view');
        Route::get('/analytics/datasets', [AnalyticsBacktestController::class, 'datasets'])->middleware('permission:analytics.view');
        Route::post('/analytics/datasets', [AnalyticsBacktestController::class, 'buildDataset'])->middleware('permission:analytics.manage');
        Route::get('/analytics/datasets/{dataset}', [AnalyticsBacktestController::class, 'showDataset'])->middleware('permission:analytics.view');
        Route::get('/analytics/snapshots', [AnalyticsBacktestController::class, 'snapshots'])->middleware('permission:analytics.view');
        Route::post('/analytics/snapshots', [AnalyticsBacktestController::class, 'snapshot'])->middleware('permission:analytics.manage');
        Route::get('/analytics/snapshots/{snapshot}/export', [AnalyticsBacktestController::class, 'exportSnapshot'])->middleware('permission:analytics.export');
        Route::get('/analytics/trades', [AnalyticsBacktestController::class, 'tradeExplorer'])->middleware('permission:analytics.view');
        Route::get('/analytics/reports', [AnalyticsBacktestController::class, 'reports'])->middleware('permission:analytics.view');
        Route::post('/analytics/reports', [AnalyticsBacktestController::class, 'createReport'])->middleware('permission:analytics.manage');
        Route::post('/analytics/promote', [AnalyticsBacktestController::class, 'refusePromote'])->middleware('permission:analytics.manage');
        Route::post('/analytics/compare', [AnalyticsBacktestController::class, 'compare'])->middleware('permission:analytics.manage');
        Route::get('/analytics/comparisons', [AnalyticsBacktestController::class, 'comparisons'])->middleware('permission:analytics.view');

        Route::get('/backtest/health', [AnalyticsBacktestController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/backtest/queue', [AnalyticsBacktestController::class, 'queueStats'])->middleware('permission:backtest.view');
        Route::post('/backtest/queue/process', [AnalyticsBacktestController::class, 'processQueue'])->middleware('permission:backtest.run');
        Route::post('/backtest/data-snapshots', [AnalyticsBacktestController::class, 'createDataSnapshot'])->middleware('permission:backtest.run');
        Route::post('/backtest/runs', [AnalyticsBacktestController::class, 'queueBacktest'])->middleware('permission:backtest.run');
        Route::get('/backtest/runs', [AnalyticsBacktestController::class, 'runs'])->middleware('permission:backtest.view');
        Route::get('/backtest/runs/{run}', [AnalyticsBacktestController::class, 'showRun'])->middleware('permission:backtest.view');
        Route::get('/backtest/runs/{run}/evaluation', [AnalyticsBacktestController::class, 'strategyEvaluation'])->middleware('permission:backtest.view');
        Route::get('/backtest/runs/{run}/export', [AnalyticsBacktestController::class, 'exportRun'])->middleware('permission:backtest.export');

        // Phase 13 — Trade Intelligence (advisory/shadow only; zero broker writes)
        Route::get('/intelligence/health', [IntelligenceController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/intelligence/desk', [IntelligenceController::class, 'desk'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/pulse', [IntelligenceController::class, 'pulse'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/heatmap', [IntelligenceController::class, 'heatmap'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/assessments', [IntelligenceController::class, 'assessments'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/assess', [IntelligenceController::class, 'assess'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/assessments/{assessment}', [IntelligenceController::class, 'showAssessment'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/opportunities', [IntelligenceController::class, 'opportunities'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/board', [IntelligenceController::class, 'board'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/calendar', [IntelligenceController::class, 'calendar'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/news', [IntelligenceController::class, 'news'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/analyze', [IntelligenceController::class, 'analyze'])->middleware('permission:intelligence.analyze');
        Route::post('/intelligence/chat', [IntelligenceController::class, 'chat'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/calibration', [IntelligenceController::class, 'calibration'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/calibration/samples', [IntelligenceController::class, 'addCalibrationSample'])->middleware('permission:intelligence.manage');
        Route::get('/intelligence/usage', [IntelligenceController::class, 'usage'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/research', [IntelligenceController::class, 'research'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/settings', [IntelligenceController::class, 'settings'])->middleware('permission:intelligence.view');
        Route::put('/intelligence/settings', [IntelligenceController::class, 'updateSettings'])->middleware('permission:intelligence.manage');
        Route::get('/intelligence/queue', [IntelligenceController::class, 'queueStats'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/queue/process', [IntelligenceController::class, 'processQueue'])->middleware('permission:intelligence.manage');
        Route::post('/intelligence/mutate', [IntelligenceController::class, 'refuseMutate'])->middleware('permission:intelligence.manage');

        // Phase 17 — Advanced Market Intelligence (extends Phase 13; advisory/shadow only)
        Route::get('/intelligence/advanced/health', [AdvancedIntelligenceController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/intelligence/advanced/desk', [AdvancedIntelligenceController::class, 'desk'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/advanced/assess', [AdvancedIntelligenceController::class, 'assess'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/advanced/snapshots', [AdvancedIntelligenceController::class, 'snapshots'])->middleware('permission:intelligence.view');
        Route::get('/intelligence/advanced/snapshots/{snapshot}', [AdvancedIntelligenceController::class, 'showSnapshot'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/advanced/mtf', [AdvancedIntelligenceController::class, 'mtf'])->middleware('permission:intelligence.analyze');
        Route::post('/intelligence/advanced/features', [AdvancedIntelligenceController::class, 'features'])->middleware('permission:intelligence.analyze');
        Route::post('/intelligence/advanced/analogs', [AdvancedIntelligenceController::class, 'analogs'])->middleware('permission:intelligence.analyze');
        Route::post('/intelligence/advanced/suitability', [AdvancedIntelligenceController::class, 'suitability'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/advanced/memory', [AdvancedIntelligenceController::class, 'memory'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/advanced/memory/post-trade', [AdvancedIntelligenceController::class, 'postTradeMemory'])->middleware('permission:intelligence.analyze');
        Route::get('/intelligence/advanced/evidence', [AdvancedIntelligenceController::class, 'evidence'])->middleware('permission:intelligence.view');
        Route::post('/intelligence/advanced/chat', [AdvancedIntelligenceController::class, 'chat'])->middleware('permission:intelligence.analyze');
        Route::post('/intelligence/advanced/mutate', [AdvancedIntelligenceController::class, 'refuseMutate'])->middleware('permission:intelligence.manage');

        // Phase 14 — Automated DEMO Trading Orchestrator (OFF|DRY_RUN|DEMO_AUTO; no LIVE_AUTO)
        Route::get('/automation/health', [AutomationController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/automation/control-center', [AutomationController::class, 'controlCenter'])->middleware('permission:automation.view');
        Route::post('/automation/preflight', [AutomationController::class, 'preflight'])->middleware('permission:automation.view');
        Route::get('/automation/profiles', [AutomationController::class, 'profiles'])->middleware('permission:automation.view');
        Route::post('/automation/profiles', [AutomationController::class, 'createProfile'])->middleware('permission:automation.manage');
        Route::post('/automation/profiles/{profile}/validate', [AutomationController::class, 'validateProfile'])->middleware('permission:automation.manage');
        Route::post('/automation/profiles/{profile}/activate', [AutomationController::class, 'activateProfile'])->middleware('permission:automation.manage');
        Route::put('/automation/profiles/{profile}', [AutomationController::class, 'reviseProfile'])->middleware('permission:automation.manage');
        Route::post('/automation/start/step1', [AutomationController::class, 'startStep1'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/start/step2', [AutomationController::class, 'startStep2'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/pause', [AutomationController::class, 'pause'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/resume', [AutomationController::class, 'resume'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/stop', [AutomationController::class, 'stop'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/kill-switch', [AutomationController::class, 'killSwitch'])->middleware('permission:automation.kill');
        Route::post('/automation/sessions/{session}/recover', [AutomationController::class, 'recover'])->middleware('permission:automation.operate');
        Route::post('/automation/sessions/{session}/tick', [AutomationController::class, 'tick'])->middleware('permission:automation.operate');
        Route::get('/automation/sessions', [AutomationController::class, 'sessions'])->middleware('permission:automation.view');
        Route::get('/automation/sessions/{session}', [AutomationController::class, 'showSession'])->middleware('permission:automation.view');
        Route::get('/automation/workflows', [AutomationController::class, 'workflows'])->middleware('permission:automation.view');
        Route::get('/automation/workflows/{workflow}', [AutomationController::class, 'showWorkflow'])->middleware('permission:automation.view');
        Route::get('/automation/events', [AutomationController::class, 'events'])->middleware('permission:automation.view');
        Route::get('/automation/rejections', [AutomationController::class, 'rejections'])->middleware('permission:automation.view');
        Route::get('/automation/executions', [AutomationController::class, 'executions'])->middleware('permission:automation.view');
        Route::get('/automation/notifications', [AutomationController::class, 'notifications'])->middleware('permission:automation.view');
        Route::post('/automation/settings/enable-auto-demo', [AutomationController::class, 'enableAutoDemoSetting'])->middleware('permission:automation.manage');
        Route::post('/automation/live-auto', [AutomationController::class, 'refuseLiveAuto'])->middleware('permission:automation.manage');

        // Phase 15 — Validation, Observability & Production Hardening
        Route::get('/observability/health', [ObservabilityController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/observability/operations', [ObservabilityController::class, 'operations'])->middleware('permission:observability.view');
        Route::get('/observability/metrics', [ObservabilityController::class, 'metrics'])->middleware('permission:observability.view');
        Route::post('/observability/metrics', [ObservabilityController::class, 'metrics'])->middleware('permission:observability.manage');
        Route::get('/observability/health-history', [ObservabilityController::class, 'healthHistory'])->middleware('permission:observability.view');
        Route::post('/observability/watchdog', [ObservabilityController::class, 'watchdog'])->middleware('permission:observability.operate');
        Route::get('/observability/alerts', [ObservabilityController::class, 'alerts'])->middleware('permission:observability.view');
        Route::post('/observability/alerts', [ObservabilityController::class, 'raiseAlert'])->middleware('permission:observability.operate');
        Route::post('/observability/alerts/{alert}/ack', [ObservabilityController::class, 'ackAlert'])->middleware('permission:observability.operate');
        Route::post('/observability/alerts/{alert}/resolve', [ObservabilityController::class, 'resolveAlert'])->middleware('permission:observability.operate');
        Route::get('/observability/validation-lab', [ObservabilityController::class, 'validationLab'])->middleware('permission:observability.view');
        Route::post('/observability/validation-sessions', [ObservabilityController::class, 'startValidation'])->middleware('permission:observability.manage');
        Route::post('/observability/validation-sessions/{session}/observe', [ObservabilityController::class, 'observeValidation'])->middleware('permission:observability.manage');
        Route::get('/observability/data-quality', [ObservabilityController::class, 'dataQuality'])->middleware('permission:observability.view');
        Route::post('/observability/data-quality', [ObservabilityController::class, 'dataQuality'])->middleware('permission:observability.operate');
        Route::post('/observability/drift', [ObservabilityController::class, 'drift'])->middleware('permission:observability.manage');
        Route::post('/observability/backup', [ObservabilityController::class, 'backup'])->middleware('permission:observability.manage');
        Route::get('/observability/disaster-recovery', [ObservabilityController::class, 'disasterRecovery'])->middleware('permission:observability.view');
        Route::get('/observability/circuits', [ObservabilityController::class, 'circuits'])->middleware('permission:observability.view');
        Route::post('/observability/circuits/event', [ObservabilityController::class, 'circuitEvent'])->middleware('permission:observability.operate');
        Route::get('/observability/resources', [ObservabilityController::class, 'resources'])->middleware('permission:observability.view');
        Route::get('/observability/scorecard', [ObservabilityController::class, 'scorecard'])->middleware('permission:observability.view');
        Route::get('/observability/env', [ObservabilityController::class, 'envCheck'])->middleware('permission:observability.view');
        Route::get('/observability/incidents', [ObservabilityController::class, 'incidents'])->middleware('permission:observability.view');
        Route::post('/observability/incidents', [ObservabilityController::class, 'openIncident'])->middleware('permission:observability.operate');
        Route::get('/observability/comparisons', [ObservabilityController::class, 'comparisons'])->middleware('permission:observability.view');
        Route::get('/observability/risk', [ObservabilityController::class, 'riskOps'])->middleware('permission:observability.view');
        Route::get('/observability/execution-quality', [ObservabilityController::class, 'executionQuality'])->middleware('permission:observability.view');
        Route::get('/observability/reconciliation', [ObservabilityController::class, 'reconciliationOps'])->middleware('permission:observability.view');
        Route::get('/observability/queue', [ObservabilityController::class, 'queueOps'])->middleware('permission:observability.view');
        Route::get('/observability/server', [ObservabilityController::class, 'serverOps'])->middleware('permission:observability.view');
        Route::get('/observability/failure-scenarios', [ObservabilityController::class, 'failureScenarios'])->middleware('permission:observability.view');
        Route::post('/observability/live-production', [ObservabilityController::class, 'refuseLiveProduction'])->middleware('permission:observability.manage');

        // Phase 16 — Strategy Governance (DEMO-only; AI cannot approve/deploy)
        Route::get('/governance/health', [GovernanceController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/governance/lifecycle', [GovernanceController::class, 'lifecycleDoc'])->middleware('permission:governance.view');
        Route::get('/governance/dashboard', [GovernanceController::class, 'dashboard'])->middleware('permission:governance.view');
        Route::get('/governance/versions', [GovernanceController::class, 'versions'])->middleware('permission:governance.view');
        Route::post('/governance/versions', [GovernanceController::class, 'registerVersion'])->middleware('permission:governance.manage');
        Route::get('/governance/versions/{version}', [GovernanceController::class, 'showVersion'])->middleware('permission:governance.view');
        Route::post('/governance/versions/{version}/transition', [GovernanceController::class, 'transition'])->middleware('permission:governance.manage');
        Route::post('/governance/versions/{version}/release-candidates', [GovernanceController::class, 'openReleaseCandidate'])->middleware('permission:governance.manage');
        Route::post('/governance/versions/{version}/evidence', [GovernanceController::class, 'buildEvidence'])->middleware('permission:governance.manage');
        Route::post('/governance/versions/{version}/validate', [GovernanceController::class, 'evaluateValidation'])->middleware('permission:governance.manage');
        Route::post('/governance/versions/{version}/approvals', [GovernanceController::class, 'startApproval'])->middleware('permission:governance.approve');
        Route::post('/governance/approvals/{approval}/step', [GovernanceController::class, 'approvalStep'])->middleware('permission:governance.approve');
        Route::post('/governance/policies', [GovernanceController::class, 'createPolicy'])->middleware('permission:governance.manage');
        Route::post('/governance/comparisons', [GovernanceController::class, 'compare'])->middleware('permission:governance.view');
        Route::get('/governance/lab', [GovernanceController::class, 'lab'])->middleware('permission:governance.lab');
        Route::post('/governance/lab/experiments', [GovernanceController::class, 'runLab'])->middleware('permission:governance.lab');
        Route::post('/governance/portfolios', [GovernanceController::class, 'createPortfolio'])->middleware('permission:governance.manage');
        Route::post('/governance/change-requests', [GovernanceController::class, 'createChangeRequest'])->middleware('permission:governance.manage');
        Route::post('/governance/change-requests/{changeRequest}/reject', [GovernanceController::class, 'rejectChangeRequest'])->middleware('permission:governance.approve');
        Route::post('/governance/live-deploy', [GovernanceController::class, 'refuseLiveDeploy'])->middleware('permission:governance.manage');
        Route::post('/governance/ai-approve', [GovernanceController::class, 'refuseAiApprove'])->middleware('permission:governance.manage');

        // Phase 18 — Multi-Broker / Multi-Account Fleet (routes into Phase 10; no order_send)
        Route::get('/fleet/health', [FleetController::class, 'health'])->middleware('permission:trading.read');
        Route::get('/fleet/dashboard', [FleetController::class, 'dashboard'])->middleware('permission:fleet.view');
        Route::post('/fleet/providers', [FleetController::class, 'registerProvider'])->middleware('permission:fleet.manage');
        Route::post('/fleet/connections', [FleetController::class, 'registerConnection'])->middleware('permission:fleet.manage');
        Route::post('/fleet/accounts', [FleetController::class, 'registerAccount'])->middleware('permission:fleet.manage');
        Route::post('/fleet/accounts/{fleetAccount}/verify', [FleetController::class, 'verifyAccount'])->middleware('permission:fleet.operate');
        Route::post('/fleet/accounts/{fleetAccount}/terminals', [FleetController::class, 'registerTerminal'])->middleware('permission:fleet.manage');
        Route::post('/fleet/terminals/{fleetTerminal}/supervise', [FleetController::class, 'superviseTerminal'])->middleware('permission:fleet.operate');
        Route::post('/fleet/instruments/map', [FleetController::class, 'mapInstrument'])->middleware('permission:fleet.manage');
        Route::post('/fleet/instruments/refresh-specs', [FleetController::class, 'refreshSpecs'])->middleware('permission:fleet.operate');
        Route::post('/fleet/portfolios', [FleetController::class, 'createPortfolio'])->middleware('permission:fleet.manage');
        Route::post('/fleet/portfolios/{tradingPortfolio}/memberships', [FleetController::class, 'addMembership'])->middleware('permission:fleet.manage');
        Route::post('/fleet/portfolios/{tradingPortfolio}/allocations', [FleetController::class, 'activateAllocation'])->middleware('permission:fleet.manage');
        Route::get('/fleet/portfolios/{tradingPortfolio}/analytics', [FleetController::class, 'portfolioAnalytics'])->middleware('permission:fleet.view');
        Route::post('/fleet/accounts/{fleetAccount}/assignments', [FleetController::class, 'assignStrategy'])->middleware('permission:fleet.manage');
        Route::post('/fleet/risk-locks', [FleetController::class, 'createRiskLock'])->middleware('permission:fleet.risk');
        Route::post('/fleet/accounts/{fleetAccount}/route', [FleetController::class, 'routeExecution'])->middleware('permission:fleet.route');
        Route::post('/fleet/accounts/{fleetAccount}/management-gate', [FleetController::class, 'managementGate'])->middleware('permission:fleet.operate');
        Route::post('/fleet/accounts/{fleetAccount}/reconcile', [FleetController::class, 'reconcile'])->middleware('permission:fleet.reconcile');
        Route::post('/fleet/health/capture', [FleetController::class, 'healthCapture'])->middleware('permission:fleet.view');
        Route::post('/fleet/accounts/{fleetAccount}/automation-scope', [FleetController::class, 'automationScope'])->middleware('permission:fleet.operate');
        Route::post('/fleet/emergency', [FleetController::class, 'emergency'])->middleware('permission:fleet.emergency');
        Route::post('/fleet/valuation', [FleetController::class, 'valuation'])->middleware('permission:fleet.view');
        Route::post('/fleet/nodes', [FleetController::class, 'registerNode'])->middleware('permission:fleet.manage');
        Route::post('/fleet/nodes/{tradingNode}/leases', [FleetController::class, 'acquireLease'])->middleware('permission:fleet.operate');
        Route::post('/fleet/ai-route', [FleetController::class, 'refuseAiRoute'])->middleware('permission:fleet.manage');
        Route::post('/fleet/live-auto', [FleetController::class, 'refuseLiveAuto'])->middleware('permission:fleet.manage');
        Route::post('/fleet/copy-trading', [FleetController::class, 'refuseCopyTrading'])->middleware('permission:fleet.manage');

        // Phase 19 — Production Hardening / Ops Control Center
        Route::get('/hardening/matrix', [HardeningController::class, 'matrix'])->middleware('permission:hardening.view');
        Route::get('/hardening/ops', [HardeningController::class, 'ops'])->middleware('permission:hardening.view');
        Route::get('/hardening/trading-readiness', [HardeningController::class, 'tradingReadinessSeparated'])->middleware('permission:hardening.view');
        Route::get('/hardening/environments', [HardeningController::class, 'environments'])->middleware('permission:hardening.view');
        Route::post('/hardening/environments/validate', [HardeningController::class, 'environments'])->middleware('permission:hardening.manage');
        Route::get('/hardening/secrets', [HardeningController::class, 'secrets'])->middleware('permission:hardening.secrets');
        Route::post('/hardening/secrets/rotate', [HardeningController::class, 'rotateSecret'])->middleware('permission:hardening.secrets');
        Route::get('/hardening/identity', [HardeningController::class, 'identity'])->middleware('permission:hardening.view');
        Route::post('/hardening/identity/services', [HardeningController::class, 'registerService'])->middleware('permission:hardening.manage');
        Route::post('/hardening/identity/nodes', [HardeningController::class, 'registerNode'])->middleware('permission:hardening.manage');
        Route::post('/hardening/mfa/challenge', [HardeningController::class, 'mfaChallenge'])->middleware('permission:hardening.operate');
        Route::post('/hardening/mfa/verify', [HardeningController::class, 'mfaVerify'])->middleware('permission:hardening.operate');
        Route::get('/hardening/security', [HardeningController::class, 'security'])->middleware('permission:hardening.view');
        Route::get('/hardening/dependencies', [HardeningController::class, 'dependencies'])->middleware('permission:hardening.view');
        Route::get('/hardening/queues', [HardeningController::class, 'queues'])->middleware('permission:hardening.view');
        Route::post('/hardening/queues', [HardeningController::class, 'queues'])->middleware('permission:hardening.operate');
        Route::post('/hardening/queues/dequeue', [HardeningController::class, 'dequeue'])->middleware('permission:hardening.operate');
        Route::post('/hardening/queues/{job}/complete', [HardeningController::class, 'completeJob'])->middleware('permission:hardening.operate');
        Route::get('/hardening/workers', [HardeningController::class, 'workers'])->middleware('permission:hardening.view');
        Route::post('/hardening/workers', [HardeningController::class, 'registerWorker'])->middleware('permission:hardening.manage');
        Route::post('/hardening/workers/{worker}', [HardeningController::class, 'workerAction'])->middleware('permission:hardening.operate');
        Route::get('/hardening/dr', [HardeningController::class, 'dr'])->middleware('permission:hardening.view');
        Route::post('/hardening/backup', [HardeningController::class, 'backup'])->middleware('permission:hardening.manage');
        Route::post('/hardening/isolated-restore', [HardeningController::class, 'isolatedRestore'])->middleware('permission:hardening.manage');
        Route::get('/hardening/deploy', [HardeningController::class, 'deploy'])->middleware('permission:hardening.view');
        Route::post('/hardening/deploy', [HardeningController::class, 'registerDeploy'])->middleware('permission:hardening.deploy');
        Route::post('/hardening/deploy/{deploy}', [HardeningController::class, 'deployAction'])->middleware('permission:hardening.deploy');
        Route::get('/hardening/failover', [HardeningController::class, 'failover'])->middleware('permission:hardening.view');
        Route::get('/hardening/safe-modes', [HardeningController::class, 'safeModes'])->middleware('permission:hardening.view');
        Route::post('/hardening/safe-modes', [HardeningController::class, 'activateSafeMode'])->middleware('permission:hardening.operate');
        Route::post('/hardening/safe-modes/{safeMode}/clear', [HardeningController::class, 'clearSafeMode'])->middleware('permission:hardening.operate');
        Route::get('/hardening/capacity', [HardeningController::class, 'capacity'])->middleware('permission:hardening.view');
        Route::get('/hardening/soak', [HardeningController::class, 'soak'])->middleware('permission:hardening.view');
        Route::post('/hardening/soak/run', [HardeningController::class, 'runSoak'])->middleware('permission:hardening.manage');
        Route::post('/hardening/chaos/run', [HardeningController::class, 'runChaos'])->middleware('permission:hardening.manage');
        Route::get('/hardening/windows', [HardeningController::class, 'windowsHardening'])->middleware('permission:hardening.view');
        Route::post('/hardening/ai-mutate', [HardeningController::class, 'refuseAiMutation'])->middleware('permission:hardening.manage');
        Route::post('/hardening/live-auto', [HardeningController::class, 'refuseLiveAuto'])->middleware('permission:hardening.manage');
    });
});
