import { Fragment, useCallback, useState } from "react";
import { AlertOctagon, Bell, Check, Download, FileText, ShieldAlert } from "lucide-react";
import { useService } from "../hooks/useService";
import { services } from "../services/mockServices";
import { DataTable, DirectionBadge, EnvironmentBadge, ErrorState, FilterBar, LoadingState, MetricCard, PageHeader, Panel, PnLDisplay, RiskGauge, StatusBadge } from "../components/ui";
import { EquityChart, PerformanceChart } from "../components/TradingCharts";
import { useSimulation } from "../context/simulationState";

const Button = ({ children, tone = "", disabled = false, onClick }: { children: React.ReactNode; tone?: string; disabled?: boolean; onClick?: () => void }) => (
  <button className={`btn ${tone}`} disabled={disabled} onClick={onClick}>
    {children}
  </button>
);

export function PendingOrders() {
  const load = useCallback(() => services.orders.getPendingOrders(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Pending simulation orders are unavailable."} />;
  return (
    <>
      <PageHeader title="Pending Orders" description="Virtual instructions awaiting mock market conditions." actions={<EnvironmentBadge />} />
      <Panel title="Simulation pending orders" subtitle="No order is transmitted externally">
        <FilterBar />
        <DataTable
          columns={["Ticket", "Symbol", "Order Type", "Volume", "Entry", "SL", "TP", "Expiry", "Strategy", "Created", "Status", "Actions"]}
          rows={data.map((order) => [
            order.ticket,
            order.symbol,
            order.type,
            order.volume.toFixed(2),
            order.entry,
            order.stopLoss,
            order.takeProfit,
            order.expiry ?? "GTC",
            order.strategy ?? "Manual",
            order.createdAt ?? "—",
            <StatusBadge key={`${order.id}-status`} tone="warning">
              {order.status}
            </StatusBadge>,
            <div key={`${order.id}-actions`} className="row-actions">
              <button>View</button>
              <button>Modify</button>
              <button>Cancel</button>
            </div>,
          ])}
        />
      </Panel>
    </>
  );
}
export function TradeHistory() {
  const load = useCallback(() => services.trades.getTrades(), []);
  const { data, loading, error } = useService(load);
  const [selected, setSelected] = useState(false);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Trade history is unavailable."} />;
  return (
    <>
      <PageHeader title="Trade History" description="Closed simulation deals with complete cost and outcome accounting." />
      <Panel title="Closed trades" subtitle="Simulation ledger">
        <FilterBar>
          {["Date range", "Account", "Symbol", "Strategy", "Direction", "Result"].map((x) => (
            <Button key={x} tone="ghost">
              {x}
            </Button>
          ))}
        </FilterBar>
        <DataTable
          columns={["Ticket", "Symbol", "Direction", "Strategy", "Volume", "Entry", "Exit", "SL", "TP", "Gross P/L", "Commission", "Swap", "Net P/L", "Duration", "Closed At"]}
          rows={data.map((t) => [
            <button key={`${t.ticket}-ticket`} className="link" onClick={() => setSelected(true)}>
              {t.ticket}
            </button>,
            t.symbol,
            <DirectionBadge key={`${t.ticket}-direction`} value={t.direction} />,
            t.strategy,
            t.volume,
            t.entry,
            t.exit,
            t.stopLoss,
            t.takeProfit,
            <PnLDisplay key={`${t.ticket}-gross-pnl`} value={t.grossPnl} />,
            t.commission,
            t.swap,
            <PnLDisplay key={`${t.ticket}-net-pnl`} value={t.netPnl} />,
            t.duration,
            t.closedAt,
          ])}
        />
      </Panel>
      {selected && (
        <div className="drawer">
          <button className="drawer-close" onClick={() => setSelected(false)}>
            ×
          </button>
          <span className="eyebrow">TRADE DETAIL</span>
          <h2>SIM-10321</h2>
          <p>This deal was generated by the simulation ledger. No broker fill exists.</p>
          <div className="detail-list">
            {[
              ["Order", "SIM-10320"],
              ["Deal", "DEMO-D-8751"],
              ["Position", "SIM-P-319"],
              ["Environment", "SIMULATION"],
              ["Result", "+$490.40"],
            ].map(([l, v]) => (
              <div key={l}>
                <span>{l}</span>
                <strong>{v}</strong>
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  );
}
export function RiskManagement() {
  const load = useCallback(() => Promise.all([services.risk.getProfile(), services.risk.getEvents()]), []);
  const { data, loading, error } = useService(load);
  const { stopped, setStopped } = useSimulation();
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Risk data is unavailable."} />;
  const [p, events] = data;
  return (
    <>
      <PageHeader
        title="Risk Management"
        description="Portfolio safeguards and simulation-only emergency controls."
        actions={
          <Button tone="danger" onClick={() => setStopped(!stopped)}>
            <AlertOctagon />
            {stopped ? "RESUME SIMULATION" : "EMERGENCY STOP"}
          </Button>
        }
      />
      {stopped && (
        <div className="danger-banner">
          <ShieldAlert /> Simulation halted. No mock orders or signals will be accepted until resumed.
        </div>
      )}
      <div className="gauge-grid">
        <RiskGauge label="Daily loss usage" value={1.2} limit={p.maxDailyLoss} />
        <RiskGauge label="Weekly loss usage" value={2.8} limit={p.maxWeeklyLoss} />
        <RiskGauge label="Current drawdown" value={2.4} limit={p.maxDrawdown} />
        <RiskGauge label="Open account risk" value={3.2} limit={p.maxOpenRisk} />
        <RiskGauge label="Margin level" value={1846} limit={p.minMarginLevel} inverse />
      </div>
      <div className="two-grid">
        <Panel title="Risk profile" subtitle="Balanced Simulation">
          <div className="settings-list">
            {Object.entries(p).map(([k, v]) => (
              <div key={k}>
                <span>{k.replace(/([A-Z])/g, " $1")}</span>
                <strong>{v}</strong>
              </div>
            ))}
          </div>
        </Panel>
        <Panel title="Risk events" subtitle="Latest simulation controls">
          <div className="event-list">
            {events.map((e) => (
              <div key={e.id}>
                <StatusBadge tone={e.severity === "WARNING" ? "warning" : "info"}>{e.severity}</StatusBadge>
                <p>
                  <strong>{e.title}</strong>
                  <span>{e.detail}</span>
                  <small>{e.occurredAt}</small>
                </p>
              </div>
            ))}
          </div>
        </Panel>
      </div>
      <Panel title="Portfolio & exposure" subtitle="Concentration and correlation overview">
        <div className="exposure-grid">
          {[
            ["USD currency exposure", 72],
            ["XAUUSD symbol risk", 38],
            ["Long exposure", 61],
            ["Short exposure", 39],
            ["Trend strategies", 44],
            ["Forex asset class", 57],
          ].map(([l, v]) => (
            <div key={l}>
              <span>{l}</span>
              <div>
                <i style={{ width: `${v}%` }} />
              </div>
              <strong>{v}%</strong>
            </div>
          ))}
        </div>
        <div className="placeholder-note">Correlation matrix and cross-account exposure become authoritative after backend portfolio aggregation in a future phase.</div>
      </Panel>
    </>
  );
}
export function PaperTrading() {
  const load = useCallback(() => services.paper.getSnapshot(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Paper trading data is unavailable."} />;
  return (
    <>
      <PageHeader title="Paper Trading" description="Virtual capital workspace using retained mock data." actions={<StatusBadge tone="info">SIMULATED DATA</StatusBadge>} />
      <div className="metrics-grid">
        <MetricCard label="Virtual Balance" value={`$${data.balance.toLocaleString()}`} />
        <MetricCard label="Virtual Equity" value={`$${data.equity.toLocaleString()}`} />
        <MetricCard label="Open Paper Positions" value={data.positions.length} />
        <MetricCard label="Paper P/L" value={<PnLDisplay value={data.profit} />} />
      </div>
      <div className="info-banner">
        <FileText /> Paper trading remains a deterministic mock module; no Phase 2 persistence API is available for this area.
      </div>
      <Panel title="Paper positions" subtitle="Virtual ledger">
        <DataTable
          columns={["Ticket", "Symbol", "Direction", "Volume", "Entry", "Current", "P/L", "Opened"]}
          rows={data.positions.map((position) => [
            position.ticket,
            position.symbol,
            <DirectionBadge key={`${position.id}-direction`} value={position.direction} />,
            position.volume.toFixed(2),
            position.entry,
            position.current,
            <PnLDisplay key={`${position.id}-pnl`} value={position.profit} />,
            position.openedAt,
          ])}
        />
      </Panel>
    </>
  );
}
export function Analytics() {
  const load = useCallback(() => services.analytics.getEquitySeries(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Analytics data is unavailable."} />;
  return (
    <>
      <PageHeader title="Performance Analytics" description="Professional simulation breakdown across trading dimensions." />
      <div className="metrics-grid">
        <MetricCard label="Average R Multiple" value="1.84R" />
        <MetricCard label="Profit Factor" value="1.72" />
        <MetricCard label="Max Drawdown" value="7.4%" />
        <MetricCard label="Long vs Short" value="58 / 42" />
        <MetricCard label="Winning vs Losing" value="68 / 32" />
      </div>
      <div className="two-grid">
        <Panel title="Equity and drawdown" subtitle="12-month simulation">
          <EquityChart data={data} />
        </Panel>
        <Panel title="Weekday performance" subtitle="Net P/L by day">
          <PerformanceChart />
        </Panel>
      </div>
      {["Strategy", "Symbol", "Timeframe", "Weekday", "Trading Session"].map((d, i) => (
        <Panel key={d} title={`Performance by ${d}`} subtitle="Simulation aggregation">
          <div className="ranking-list">
            {["EMA Pullback", "Market Structure", "London Breakout", "Gold Scalper"].map((x, n) => (
              <div key={`${d}-${x}`}>
                <span>{n + 1}</span>
                <p>
                  <strong>{i ? `${d} segment ${n + 1}` : x}</strong>
                  <small>
                    {18 + n * 7} trades · {(64 - n * 2.4).toFixed(1)}% win rate
                  </small>
                </p>
                <b className="positive">+${(4280 - n * 620).toLocaleString()}</b>
              </div>
            ))}
          </div>
        </Panel>
      ))}
    </>
  );
}
export function Reports() {
  const [category, setCategory] = useState("Daily");
  return (
    <>
      <PageHeader
        title="Reports"
        description="Review simulation summaries before future server-side export support."
        actions={
          <Button disabled>
            <Download /> Export unavailable
          </Button>
        }
      />
      <div className="report-categories">
        {["Daily", "Weekly", "Monthly", "Account", "Strategy", "Risk", "Execution"].map((x) => (
          <button key={x} className={category === x ? "active" : ""} onClick={() => setCategory(x)}>
            <FileText />
            <span>{x}</span>
          </button>
        ))}
      </div>
      <Panel title={`${category} Report Preview`} subtitle="September 17, 2026 · SIMULATION">
        <div className="report-preview">
          <div>
            <span>NEXA TRADEBOT</span>
            <EnvironmentBadge />
          </div>
          <h2>{category} Trading Performance</h2>
          <p>Prepared from deterministic mock records retained in Phase 2.</p>
          <div className="report-kpis">
            <div>
              <span>Net P/L</span>
              <strong className="positive">+$1,842.30</strong>
            </div>
            <div>
              <span>Trades</span>
              <strong>12</strong>
            </div>
            <div>
              <span>Win rate</span>
              <strong>68.4%</strong>
            </div>
            <div>
              <span>Risk events</span>
              <strong>1 warning</strong>
            </div>
          </div>
          <p className="placeholder-note">PDF, Excel, and CSV actions remain disabled until valid server-generated exports are implemented. No fake download is provided.</p>
        </div>
      </Panel>
    </>
  );
}
export function NewsCalendar() {
  const load = useCallback(() => services.news.getEvents(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Mock news events are unavailable."} />;
  return (
    <>
      <PageHeader title="News Calendar" description="Demonstration economic events; not a live news feed." />
      <Panel title="Thursday, September 17" subtitle="All times UTC · MOCK CALENDAR">
        <FilterBar>
          {["Currency", "Impact", "Date"].map((x) => (
            <Button key={x} tone="ghost">
              {x}
            </Button>
          ))}
        </FilterBar>
        <DataTable
          columns={["Time", "Currency", "Impact", "Event", "Previous", "Forecast", "Actual"]}
          rows={data.map((event) => [
            event.time,
            <b key={`${event.id}-currency`}>{event.currency}</b>,
            <StatusBadge key={`${event.id}-impact`} tone={event.impact === "High" ? "bad" : event.impact === "Medium" ? "warning" : "neutral"}>
              {event.impact}
            </StatusBadge>,
            event.event,
            event.previous,
            event.forecast,
            event.actual,
          ])}
        />
      </Panel>
      <div className="placeholder-note">
        <ShieldAlert /> News Trading Protection is not available. Mock calendar events do not control Phase 2 simulation activity.
      </div>
    </>
  );
}
export function MT5Accounts() {
  const load = useCallback(() => services.account.getAccounts(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Account status is unavailable."} />;
  return (
    <>
      <PageHeader title="MT5 Accounts" description="Connection inventory only. Nexa TradeBot never requests broker passwords." actions={<StatusBadge tone="bad">NOT CONNECTED</StatusBadge>} />
      <div className="account-card">
        {data.map((a) => (
          <Fragment key={a.id}>
            <div className="account-icon">XM</div>
            <div>
              <span className="eyebrow">{a.environment} ACCOUNT</span>
              <h2>{a.name}</h2>
              <p>
                {a.broker} · {a.platform}
              </p>
            </div>
            <div className="account-details">
              {[
                ["Server", a.server],
                ["Currency", a.currency],
                ["Leverage", a.leverage],
                ["Status", a.status],
              ].map(([l, v]) => (
                <p key={l}>
                  <span>{l}</span>
                  <strong>{v}</strong>
                </p>
              ))}
            </div>
            <Button disabled>Connection unavailable</Button>
          </Fragment>
        ))}
      </div>
      <div className="warning-box">
        <ShieldAlert />
        <p>
          <strong>Credential-safe foundation</strong>
          <span>No password, investor password, API secret, or terminal path is collected or stored. MT5 connectivity belongs to a later DEMO-only phase.</span>
        </p>
      </div>
    </>
  );
}
export function Notifications() {
  const load = useCallback(() => services.notifications.getNotifications(), []);
  const { data, loading, error } = useService(load);
  const [read, setRead] = useState(false);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Notifications are unavailable."} />;
  return (
    <>
      <PageHeader
        title="Notifications"
        description="Signal, risk, strategy, system, and security activity."
        actions={
          <Button tone="ghost" onClick={() => setRead(true)}>
            <Check />
            Mark all read
          </Button>
        }
      />
      <FilterBar>
        {["All", "Trade", "Signal", "Risk", "Strategy", "MT5", "News", "System", "Security"].map((x) => (
          <button key={x} className="chip">
            {x}
          </button>
        ))}
      </FilterBar>
      <Panel title="Notification center" subtitle={`${read ? 0 : data.filter((n) => !n.read).length} unread`}>
        <div className="notification-list">
          {data.map((n) => (
            <div key={n.id} className={!n.read && !read ? "unread" : ""}>
              <span className="notification-icon">
                <Bell />
              </span>
              <StatusBadge tone={n.category === "Risk" ? "warning" : n.category === "Signal" ? "purple" : "info"}>{n.category}</StatusBadge>
              <p>
                <strong>{n.title}</strong>
                <span>{n.body}</span>
              </p>
              <time>{n.time}</time>
            </div>
          ))}
        </div>
      </Panel>
    </>
  );
}
export function SystemHealthPage() {
  const load = useCallback(() => services.health.getHealth(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "System health is unavailable."} />;
  return (
    <>
      <PageHeader title="System Health" description="Operational readiness across simulation and future integration boundaries." actions={<StatusBadge tone="good">PHASE 2</StatusBadge>} />
      <div className="health-meta">
        {[
          ["App version", data.version],
          ["Last heartbeat", data.lastHeartbeat],
          ["Market update", data.lastMarketUpdate],
          ["Last signal", data.lastSignal],
        ].map(([l, v]) => (
          <div key={l}>
            <span>{l}</span>
            <strong>{v}</strong>
          </div>
        ))}
      </div>
      <div className="health-grid">
        {data.services.map((s) => (
          <article key={s.name}>
            <div className={`health-icon ${s.state.toLowerCase().replace(" ", "-")}`}>
              <span />
            </div>
            <p>
              <strong>{s.name}</strong>
              <span>{s.detail}</span>
            </p>
            <StatusBadge tone={s.state === "ONLINE" ? "good" : s.state === "NOT CONNECTED" ? "bad" : s.state === "MOCK" ? "info" : "warning"}>{s.state}</StatusBadge>
          </article>
        ))}
      </div>
    </>
  );
}
export function AuditLogs() {
  const load = useCallback(() => services.audit.getEvents(), []);
  const { data, loading, error } = useService(load);
  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Audit events are unavailable."} />;
  return (
    <>
      <PageHeader title="Audit Logs" description="Tamper-evident interface preview using simulated security events." />
      <Panel title="Activity ledger" subtitle="Activity events">
        <FilterBar>
          {["User", "Module", "Action", "Result", "Date"].map((x) => (
            <Button key={x} tone="ghost">
              {x}
            </Button>
          ))}
        </FilterBar>
        <DataTable
          columns={["Timestamp", "User", "Action", "Module", "Description", "IP", "Result"]}
          rows={data.map((event) => [
            event.timestamp,
            event.user,
            event.action,
            event.module,
            event.description,
            event.ip,
            <StatusBadge key={`${event.id}-result`} tone={event.result === "SUCCESS" ? "good" : "bad"}>
              {event.result}
            </StatusBadge>,
          ])}
        />
      </Panel>
    </>
  );
}
export function Settings() {
  const [t, setT] = useState("General");
  return (
    <>
      <PageHeader title="Settings" description="Local simulation preferences and future configuration boundaries." />
      <div className="settings-layout">
        <nav>
          {["General", "Trading", "Risk", "Notifications", "Security", "Appearance", "System"].map((x) => (
            <button key={x} className={t === x ? "active" : ""} onClick={() => setT(x)}>
              {x}
            </button>
          ))}
        </nav>
        <Panel title={`${t} Settings`} subtitle="Preference preview">
          <div className="settings-form">
            {t === "Appearance" ? (
              <>
                <div className="setting-row">
                  <p>
                    <label htmlFor="appearance-theme">
                      <strong>Color theme</strong>
                    </label>
                    <span>Dark professional terminal is the application default.</span>
                  </p>
                  <select id="appearance-theme" name="appearance-theme">
                    <option>Dark (default)</option>
                    <option>System (future)</option>
                  </select>
                </div>
                <div className="setting-row">
                  <p>
                    <label htmlFor="appearance-compact-density">
                      <strong>Compact density</strong>
                    </label>
                    <span>Optimize tables for trading workstations.</span>
                  </p>
                  <input id="appearance-compact-density" name="appearance-compact-density" type="checkbox" defaultChecked />
                </div>
              </>
            ) : (
              ["Simulation confirmations", "Sound alerts", "Desktop notifications", "Compact tables", "Risk warning banners"].map((x, i) => (
                <div key={x} className="setting-row">
                  <p>
                    <label htmlFor={`setting-${i}`}>
                      <strong>{x}</strong>
                    </label>
                    <span>{i ? "Stored locally for the demonstration." : "Require confirmation before virtual state changes."}</span>
                  </p>
                  <input id={`setting-${i}`} name={`setting-${i}`} type="checkbox" defaultChecked={i !== 1} />
                </div>
              ))
            )}
          </div>
          <Button tone="primary">Save preferences</Button>
        </Panel>
      </div>
    </>
  );
}
